# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OCRTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'GRDB.swift'
  pod 'ReachabilitySwift'
  # Pods for OCRTest

  target 'OCRTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCRTestUITests' do
    # Pods for testing
  end

end
