# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OCRiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TesseractOCRiOS'
  pod 'GPUImage'
  # Pods for OCRiOS

  target 'OCRiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCRiOSUITests' do
    # Pods for testing
  end

end
