# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'switfOCRopen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for switfOCRopen

  target 'switfOCRopenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'switfOCRopenUITests' do
    # Pods for testing
  end

end
