# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tesseractOCR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyTesseract', '~> 2.0'

  target 'tesseractOCRTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tesseractOCRUITests' do
    # Pods for testing
  end

end
