# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'socr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftOCR', :git => "https://github.com/garnele007/SwiftOCR.git", :tag => "1.2.1"
  # Pods for socr

  target 'socrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'socrUITests' do
    # Pods for testing
  end

end
